name: nornbot-pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest_unordered
          pip install pytest flake8 bandit pylint black
      - name: Run tests and linting
        run: |
          black . --check
          #pytest -v
          #flake8
          isort . --check
          #bandit -r -s B101 src test
          #pylint src/
